from prettytable import PrettyTable
import time

tabel = PrettyTable()
tabel.field_names = ["Nama", "Nim", "Prodi"]
tabel.add_row(["Fikri Abiyyu Rahman", "2409116063", "Sistem Informasi"])
print(tabel)
print("")
print("")
print("")

while True:
    print("-- ini lampu merah --")
    lampu_merah = PrettyTable()
    lampu_merah.field_names = ["Lampu Lalu Lintas"]
    lampu_merah.add_row(["🔴"])
    lampu_merah.add_row(["⚪"])
    lampu_merah.add_row(["⚪"])
    print("")
    print("")

    print(lampu_merah)
    print("1")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("10")
    time.sleep(1)
    print("")
    print("")

    print("-- Ini Lampu Kuning --")
    lampu_kuning = PrettyTable()
    lampu_kuning.field_names = ["Lampu Lalu Lintas"]
    lampu_kuning.add_row(["⚪"])
    lampu_kuning.add_row(["🟡"])
    lampu_kuning.add_row(["⚪"])
    print("")
    print("")

    print(lampu_kuning)
    print("1")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("")
    print("")

    print("-- Ini Lampu Hijau --")
    lampu_Hijau = PrettyTable()
    lampu_Hijau.field_names = ["Lampu Lalu Lintas"]
    lampu_Hijau.add_row(["⚪"])
    lampu_Hijau.add_row(["⚪"])
    lampu_Hijau.add_row(["🟢"])
    print("")
    print("")

    print(lampu_Hijau)
    print("1")
    time.sleep(1)
    print("2")
    time.sleep(1)
    print("3")
    time.sleep(1)
    print("4")
    time.sleep(1)
    print("5")
    time.sleep(1)
    print("6")
    time.sleep(1)
    print("7")
    time.sleep(1)
    print("8")
    time.sleep(1)
    print("9")
    time.sleep(1)
    print("10")
    time.sleep(1)
    print("")
    print("")